version: '3.8'

services:
  atendo-maps:
    build:
      context: .
    container_name: atendo-maps-prospector
    restart: always
    ports:
      - "3005:80"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - SCRAPER_API_KEY=${SCRAPER_API_KEY:-}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
