version: '3.8'

services:
  atendo-maps:
    build:
      context: .
      args:
        # Passa a chave da VPS para o Docker durante o build
        - API_KEY=${API_KEY}
    container_name: atendo-maps-prospector
    restart: always
    ports:
      - "3005:80"
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
